name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test -v d /p:Platform=linux ./narlangCompiler/test/test.csproj
    
    # Update nuget package
    - name: Publish Nuget
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
       PROJECT_FILE_PATH: ./narlangCompiler/narlang/narlang.csproj
       NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish VsCode Extension
      uses: lannonbr/vsce-action@master
      with:
          args: "publish -p $VSCE_TOKEN"
      env:
          working-directory: narlang_vsCode
          VSCE_TOKEN: ${{secrets.VSCE_TOKEN}}
